baseURL = "https://zikkas.github.io/imm/"
languageCode = "en-us"
title = "IMM 2025-2026 Promotion Resources"
theme = "github.com/McShelby/hugo-theme-relearn"
markup.goldmark.parser.attribute.block = true

[params]
math = true
collapsibleMenu = true
disableLandingPageButton = false
themeVariant = ["auto", "zen-light", "zen-dark"]
mathJaxInitalize = "{ \"tex\": { \"inlineMath\": [ [ \"$\", \"$\" ], [ \"\\\\(\", \"\\\\)\" ] ], \"displayMath\": [ [ \"$$\", \"$$\" ], [ \"\\\\[\", \"\\\\]\" ] ] } }"
